BSC support
eth-brownie/brownie pull request #961
Opened 2021-02-15 19:44 UTC by poolpitako

### What I did

Related issue: #

### How I did it

### How to verify it

### Checklist

- [ ] I have confirmed that my PR passes all linting checks
- [ ] I have included test cases
- [ ] I have updated the documentation
- [ ] I have added an entry to the changelog

2021-02-26 14:51 UTC, iamdefinitelyahuman requested changes

2021-02-26 14:51 UTC, iamdefinitelyahuman commented on brownie/network/contract.py
> +                f"You will not be able to call _name() on {self._name}",
```suggestion
                f"The {name} function will not be available when interacting with {self._name}",
```

2021-02-26 14:51 UTC, iamdefinitelyahuman commented on brownie/network/contract.py
> +                f"You will not be able to call _name() on {self._name}",
Generally not a fan of this but I understand why it's needed..  in a v2 need to solve this more elegantly.

2021-02-26 14:51 UTC, iamdefinitelyahuman commented on brownie/data/network-config.yaml
> +      - name: bsc-main
A more descriptive name than just `bsc-main` would be good.  Same for the testnet.

2021-03-07 21:13 UTC, iamdefinitelyahuman commented
Looks like this has caused some tests to fail.

2021-03-18 16:42 UTC, iamdefinitelyahuman approved these changes

2021-03-18 16:42 UTC, merged

2021-03-18 20:51 UTC, poolpitako commented
@iamdefinitelyahuman ouch. sorry :(
Thanks for updating the pr!